// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZwyV6tLatb1lNv_iX6Xkh0nu_5QC-Rvo',
    appId: '1:839507093658:web:e2d2d6d08422ab72909723',
    messagingSenderId: '839507093658',
    projectId: 'instagram-flutter-ad9b1',
    authDomain: 'instagram-flutter-ad9b1.firebaseapp.com',
    storageBucket: 'instagram-flutter-ad9b1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5y4tfNoJl-kadEwtEXcNYzPBmdavW3Cs',
    appId: '1:839507093658:android:b76deb9322e958d8909723',
    messagingSenderId: '839507093658',
    projectId: 'instagram-flutter-ad9b1',
    storageBucket: 'instagram-flutter-ad9b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDqm_SvIHIn-y5AhQ0spyL5lhkoilApS8',
    appId: '1:839507093658:ios:2c316d570f05ea4f909723',
    messagingSenderId: '839507093658',
    projectId: 'instagram-flutter-ad9b1',
    storageBucket: 'instagram-flutter-ad9b1.appspot.com',
    iosBundleId: 'com.sultanammar.instagramFlutter',
  );
}
